name: .NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test-api-identity:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - solution_path: FastBite.Identity
            solution_file: FastBite.Identity.slnx
          - solution_path: FastBite.MenuCatalog
            solution_file: FastBite.MenuCatalog.sln
          - solution_path: FastBite.DeliveryOrdering
            solution_file: FastBite.DeliveryOrdering.slnx

    defaults:
      run:
        working-directory: ${{matrix.solution_path}}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # Update this if you are using .NET 7 or 9
        
    - name: Restore dependencies
      run: dotnet restore ${{ matrix.solution_file }}
      
    - name: Build Solution
      run: dotnet build --no-restore --configuration Release ${{ matrix.solution_file }}
      
    - name: Run Tests
      # Runs all test projects included in the solution
      run: dotnet test --no-build --verbosity normal --configuration Release ${{ matrix.solution_file }}